[package]
name = "cwhelper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
cosmwasm-std = { version = "1.5.3" }
cw20 = { version = "1.1.1" }
cw20-base = { version = "1.1.1", features = ["library"] }

[dev-dependencies]
cw-multi-test = "0.13.4"
